### PR TITLE
License compliance and headers format review

### PR DESCRIPTION
**Pull request by acmlira**
To solve SDL license (GPLv3) compliance error (#23 merge request to indirectly solve #14) we changed:
- Litebase license to LGPL-2.1-only
- Headers to SPDX standard
Headers review Still needed :sleeping:. We found some unlicensed codes and the LICENSE (archive) was added to the specific folders

### CODE REVIEW

**Comment by acmlira** [comment]
Hello everyone, last week I was talking to some people on our channels and we concluded that this header:
```java
// Copyright (C) 2000-2013 SuperWaba Ltda.
//
// TotalCross Software Development Kit
//
// This library and virtual machine is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//
// SPDX-License-Identifier: LGPL-2.1-only
```
would be better if we remove this snippet:
```java
// This library and virtual machine is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
this information is not necessary since we are under the LGPLv2.1-only license :wink:

**Comment by otavio** [comment]
Fully agree. The `SPDX-License-Identifier` is enough. 

We do as:

https://github.com/UpdateHub/updatehub/blob/master/updatehub-sdk/src/lib.rs#L1-L3

Compact and meaningful.

**Comment by acmlira** [comment]
In addition to removing this snippet:
```java
// This library and virtual machine is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
it was also removed 
```java
// TotalCross Software Development Kit
```
for redundancy reasons. I think this branch is already ready for integration to next minor :smile:

**Comment by otavio** [comment]
One remark is that it seemed SDL2 linking was moved to dynamic due the licensing but in fact, it is not required as it is licensed under zlib license and it allows static linking.

**Comment by acmlira** [comment]
You reminded me that we need SDL build script

**Pull request merged**
