### PR TITLE
Should always yields a `SSLSocket` when in `SSLSocketFactory`

### PR DESCRIPTION
**Pull request by jeffque**
## Description:
Should always yields a `SSLSocket` when in `SSLSocketFactory`. As
`SSLSocketFactory` extends `SocketFactory` and does not override the
`createSocket(String, int)` method, and calls from super classe. As
`SocketFactory` yields plain sockets...

This fix just delegates to `createSocket(String, int, int)` passing the default
`Socket.DEFAULT_OPEN_TIMEOUT` as the open timeout argument. Maybe it should be
better to call `new SSLSocket(String, int)`, but this constructor does not
exists yet.

### Related Issue:
 - Solves #101

## Motivation and Context:
Creates a SSLSocket from a SSLSocketFactory implying the default open timeout.

## Benefited Devices:
TC-SDK as a whole, also Java

## How Has This Been Tested?
 - By writing a merge request to https://gitlab.com/geosales-open-source/tc-http-conn/develop to let it be able to deal with HTTPS.
   - this MR indeed https://gitlab.com/geosales-open-source/tc-http-conn/-/merge_requests/19
- Used TC 4.3.8, but as this is pure Java should apply to any version

## Tested Devices:
 - JVM 8

### CODE REVIEW

**Comment by flsobral** [comment]
hey @jeffque , could you please rebase your branch on top of the master?

**Comment by jeffque** [comment]
@flsobral, unfortunately not now. As this is a single commit, maybe cherry-picking can be more efficient?
I am not used with github's interface to do this via mobile browser today

**Comment by jeffque** [comment]
Indeed it was created from master, I have no idea how I got those 9 other commits in my branch

**Comment by jeffque** [comment]
As this was rendered futile due to conflicts and the existing question for a rebase, I create the #114 with the same content, just changing the indentation to comply with the work of @otavio as he changed the overall code style

**Pull request closed without merging**
