### PR TITLE
Added debug info option

### PR DESCRIPTION
**Pull request by VicMisael**
## Description:
Added the debug info option for the simulator

### Related Issue:
 - Issue #231 

Please link the issue here.

## Motivation and Context:
To make the console leaner for the user

## Benefited Devices:
- Device:Simulator

## How Has This Been Tested?
- Enabled /dbginfo and see if the messages shown up, removed and see if they don't

## Tested Devices:
-Device:Simulator 

## Screenshots
With /dbginfo

image

without /dbginfo

image

### CODE REVIEW

**Review by teras — APPROVED** [review]
well done

**Review by teras — APPROVED** [review]
The code is perfect; just need to update the commit message. See the error log for details

**Comment by VicMisael** [comment]
@teras the commit message has been fixed

**Review by teras — DISMISSED** [review]

**Review by acmlira — CHANGES_REQUESTED** [review]
Hey @VicMisael your commits aren't following our guidelines, the first commits must be redone and "issue" is also not a good type due to the wide scope, I suggest "debug" for your case

**Review by acmlira — APPROVED** [review]

**Review by teras — APPROVED** [review]

**Pull request merged**
